// app.ts

function throwError(): string {
  // 例としてエラーを発生させる処理を記述
  throw new Error("This is a deliberate error!");
}

throwError(); // エラーを発生させる関数を呼び出し



